=== paul99simon/flexiteams-ar-application/flexiTeams/FlexiTeamsTests/Resources/data_pool.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs= "http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="xml.xsd"/>
	
	<xs:element name= "DataPool">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Data" type="DataType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="xml:lang"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="DataType">
		<xs:sequence>
			<xs:element name="Name" type ="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute ref="xml:id"/>
	</xs:complexType>
</xs:schema>

=== paul99simon/flexiteams-ar-application/flexiTeams/FlexiTeamsTests/Resources/1DataPool.xml
<?xml version="1.0" encoding="utf-8"?>
<DataPool   xml:lang="en"
	        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="data_pool.xsd">
  <Data xml:id="Data_0">
    <Name>Sthethescope</Name>
  </Data>
  <Data xml:id="Data_1">
    <Name>Diet details</Name>
  </Data>
  <Data xml:id="Data_2">
    <Name>Admission details</Name>
  </Data>
  <Data xml:id="Data_3">
    <Name>X-ray machine</Name>
  </Data>
  <Data xml:id="Data_4">
    <Name>lab test</Name>
  </Data>
  <Data xml:id="Data_5">
    <Name>Patient's file</Name>
  </Data>
  <Data xml:id="Data_6">
    <Name>Allergy details</Name>
  </Data>
  <Data xml:id="Data_7">
    <Name>Present medications</Name>
  </Data>
  <Data xml:id="Data_8">
    <Name>Consent form</Name>
  </Data>
  <Data xml:id="Data_9">
    <Name>Surgical dress</Name>
  </Data>
  <Data xml:id="Data_10">
    <Name>Cleaning items</Name>
  </Data>
  <Data xml:id="Data_11">
    <Name>Anesthesia tools</Name>
  </Data>
  <Data xml:id="Data_12">
    <Name>Surgical equipments</Name>
  </Data>
  <Data xml:id="Data_13">
    <Name>Wheelchair/Bed/Strecher</Name>
  </Data>
  <Data xml:id="Data_14">
    <Name>Anesthesia machine</Name>
  </Data>
  <Data xml:id="Data_15">
    <Name>Injection syringe</Name>
  </Data>
  <Data xml:id="Data_16">
    <Name>Ventilator</Name>
  </Data>
  <Data xml:id="Data_17">
    <Name>Surgical tools</Name>
  </Data>
  <Data xml:id="Data_18">
    <Name>Blood pressure monitor</Name>
  </Data>
  <Data xml:id="Data_19">
    <Name>Pulse oximeter</Name>
  </Data>
  <Data xml:id="Data_20">
    <Name>Exercise details</Name>
  </Data>
  <Data xml:id="Data_21">
    <Name>Medications</Name>
  </Data>
  <Data xml:id="Data_22">
    <Name>local anesthetic drug</Name>
  </Data>
  <Data xml:id="Data_23">
    <Name>Surgical instruments</Name>
  </Data>
</DataPool>
