=== paul99simon/flexiteams-ar-application/flexiTeams/FlexiTeamsTests/Resources/resource_pool.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs= "http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="xml.xsd"/>
	
	<xs:element name= "ResourcePool">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Resource" type="resourceType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="resourceType">
		<xs:sequence>
			<!--Personal Background-->
			<xs:element name="Photo" type="photoType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="FirstName" type="valueAttributeType" maxOccurs="unbounded"/>
			<xs:element name="LastName" type="valueAttributeType" maxOccurs="unbounded"/>
			<xs:element name="Child" type="childType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Stressor" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PersonalInfo" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>

			<!--Professional Background-->
			<xs:element name="Profession" type="valueAttributeType" maxOccurs="unbounded"/>
			<xs:element name="Department" type="valueAttributeType" maxOccurs="unbounded"/>
			<xs:element name="Training" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Qualification" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="WorkAgreement" type="workAgreementType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Studies" type ="studieType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="AdditionalJob" type="additionalJobType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="MeansOfTransport" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ProfessionalInfo" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<!--Skills-->
			<xs:element name="Skill" type="valueAttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<!--Character Traits-->
			<xs:element name="Trait" type="traitType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="xml:id"/>
		<xs:attribute name="age" type="xs:duration" use="required"/>
		<xs:attribute name="prefix" type="xs:string" use="optional"/>
		<xs:attribute name="maritalState" type="xs:string" use="required"/>
		<xs:attribute name="workExperience" type="xs:duration" use="optional"/>
		<xs:attribute name="trainingDuration" type="xs:duration" use="optional"/>
		<xs:attribute name="weeklyHours" type="xs:duration" use="required"/>
		<xs:attribute name="overtime" type="xs:duration" use="optional"/>
		<xs:attribute name="yearlyTimeOf" type="xs:duration" use="required"/>
		<xs:attribute name="yearlyEducation" type="xs:duration" use="optional"/>
		<xs:attribute name="commuteTime" type="xs:duration" use="required"/>
	</xs:complexType>

	<xs:complexType name="photoType">
		<xs:attribute name="path" type="xs:anyURI"/>
	</xs:complexType>

	<xs:complexType name="childType">
		<xs:attribute name="age" type="xs:duration" use="required"/>
	</xs:complexType>

	<xs:complexType name="workAgreementType">
		<xs:attribute name="value" type="workAgreementStringType" use="required"/>
	</xs:complexType>

	<xs:simpleType name="workAgreementStringType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-6]-(0\d|1\d|2[0-3]):[0-5]\d-(0\d|1\d|2[0-3]):[0-5]\d"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name ="studieType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="location" type="xs:string" use="optional"/>
	</xs:complexType>


	<xs:complexType name="additionalJobType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="yearlyRequiredDays" type="xs:duration" use="optional"/>
	</xs:complexType>

	<xs:complexType name ="valueAttributeType">
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name ="traitType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="percentageType" use="required"/>
	</xs:complexType>

	<xs:simpleType name ="percentageType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== paul99simon/flexiteams-ar-application/flexiTeams/FlexiTeamsTests/Resources/resource_pool_draft.xml
<?xml version="1.0" encoding="utf-8" ?>

<ResourcePool   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:noNamespaceSchemaLocation="Resource_pool.xsd">

	<Resource xml:id="Resource_1" age="P32Y" maritalState="verheiratet" weeklyHours="PT35H" yearlyTimeOf="P28D" commuteTime="PT20M" workExperience="P13Y" trainingDuration="P3Y" overtime="PT50H" yearlyEducation="P5D">
		<!--Personal Background-->
		<Photo path="../images/Resource_1.jpg"/>
		<FirstName value="Anna"/>
		<LastName value="Schmidt"/>
		<Child age="P5Y"/>
		<Child age="P3Y"/>
		<PersonalInfo value="Beide Kinder gehen in die Krankenhaus-Kita"/>
		<!--Professional Background-->
		<Profession value="Stationsschwester"/>
		<Department value="Onkologie"/>
		<Training value="Notfall Medizin"/>
		<Training value="Anästhesie"/>
		<Qualification value="Ausbildung als Labortechnikerin"/>
		<WorkAgreement value="0-22:00-06:00"/>
		<WorkAgreement value="1-22:00-06:00"/>
		<WorkAgreement value="2-22:00-06:00"/>
		<WorkAgreement value="3-22:00-06:00"/>
		<WorkAgreement value="4-22:00-06:00"/>
		<WorkAgreement value="0-06:00-12:00"/>
		<WorkAgreement value="1-06:00-12:00"/>
		<WorkAgreement value="2-06:00-12:00"/>
		<WorkAgreement value="3-06:00-12:00"/>
		<WorkAgreement value="4-06:00-12:00"/>
		<Studies name="berufsbegleitendes Studium der Medizin" location="Mainz"/>
		<AdditionalJob name="Mitglied im Personalrat"/>
		<MeansOfTransport value="öffentliche Verkehrsmittel"/>
		<MeansOfTransport value="Fahrrad"/>
		<!--Skills-->
		<Skill value="Medikamentierung"/>
		<Skill value="Diagn. Schnelltest"/>
		<Skill value="Dokumentation"/>
		<!--Character Traits-->
		<Trait name="Zuverlässigkeit" value="85"/>
		<Trait name="Entscheidungsvermögen" value="25"/>
		<Trait name="Belastungsfähigkeit" value="65"/>
		<Trait name="Veränderungsbereitschaft" value="85"/>
	</Resource>
	<Resource xml:id="Resource_2" age="P41Y" maritalState="Verheiratet" weeklyHours="PT20H" yearlyTimeOf="P20D" commuteTime="PT30M" workExperience="P14Y" yearlyEducation="P10D" overtime="PT150H" trainingDuration="P10Y">
		<!--Personal Background-->
		<Photo path=".\\images\\Resource_2.jpg"/>
		<FirstName value="Erika"/>
		<LastName value="Müller"/>
		<Child age="P11Y"/>
		<Stressor value="Pflege der kranken Eltern"/>

		<!--Professional Background-->
		<Profession value="Oberärztin"/>
		<Department value="Onkologie"/>
		<WorkAgreement value="0-06:00-12:00"/>
		<WorkAgreement value="1-06:00-12:00"/>
		<WorkAgreement value="2-06:00-12:00"/>
		<WorkAgreement value="3-06:00-12:00"/>
		<WorkAgreement value="4-06:00-12:00"/>
		<WorkAgreement value="5-06:00-12:00"/>
		<WorkAgreement value="6-06:00-12:00"/>
		<AdditionalJob name="Wissenschaftlicher Beirat" yearlyRequiredDays="P5D"/>

		<!--Skills-->
		<Skill value="Tumorentfernung"/>
		<Skill value="Anamese"/>
		<Skill value="Nachkontrolle"/>
		<Skill value="Dokumetation"/>

		<!--Character Traits-->
		<Trait name="Zuverlässigkeit" value="85"/>
		<Trait name="Entscheidungsvermögen" value="95"/>
		<Trait name="Belastungsfähigkeit" value="30"/>
		<Trait name="Veränderungsbereitschaft" value="10"/>
	</Resource>
	<Resource xml:id="Resource_3" age="P48Y" maritalState="Ledig" weeklyHours="PT15H" yearlyTimeOf="P18D" commuteTime="PT35M" workExperience="P35Y" trainingDuration="P3Y" overtime="PT10H" yearlyEducation="P3D">
		<!--Personal Background-->
		<Photo path="..\\images\\Resource_3.jpg"/>
		<FirstName value="Hilde"/>
		<LastName value="Mayer"/>
		<Child age="P21Y"/>

		<!--Professional Background-->
		<Profession value="Verwaltungsfachangestellte"/>
		<Department value="Onkologie"/>
		<Department value="Geriatrie"/>
		<WorkAgreement value="0-06:00-12:00"/>
		<WorkAgreement value="1-06:00-12:00"/>
		<WorkAgreement value="2-06:00-12:00"/>
		<!--Skills-->
		<Skill value="Schichtplanerstellung"/>
		<Skill value="Registratur"/>
		<Skill value="SAP-Abrechnungssystem Medikamente"/>

		<!--Character Traits-->
		<Trait name="Zuverlässigkeit" value="90"/>
		<Trait name="Entscheidungsvermögen" value="15"/>
		<Trait name="Belastungsfähigkeit" value="15"/>
		<Trait name="Veränderungsbereitschaft" value="10"/>
	</Resource>
</ResourcePool>
